export const FETCH_ABOUT_US_SUCCESS = 'FETCH_ABOUT_US_SUCCESS';
export const FETCH_ABOUT_US_FAILURE = 'FETCH_ABOUT_US_FAILURE';
export const UPDATE_ABOUT_US_SUCCESS = 'UPDATE_ABOUT_US_SUCCESS';
export const UPDATE_ABOUT_US_FAILURE = 'UPDATE_ABOUT_US_FAILURE';
