// src/constants/contactConstants.js
export const CONTACT_SUBMIT_REQUEST = 'CONTACT_SUBMIT_REQUEST';
export const CONTACT_SUBMIT_SUCCESS = 'CONTACT_SUBMIT_SUCCESS';
export const CONTACT_SUBMIT_FAIL = 'CONTACT_SUBMIT_FAIL';

export const CONTACT_FETCH_REQUEST = 'CONTACT_FETCH_REQUEST';
export const CONTACT_FETCH_SUCCESS = 'CONTACT_FETCH_SUCCESS';
export const CONTACT_FETCH_FAIL = 'CONTACT_FETCH_FAIL';

export const DELETE_OLD_CONTACTS_SUCCESS = 'DELETE_OLD_CONTACTS_SUCCESS'
export const DELETE_OLD_CONTACTS_FAILURE = 'DELETE_OLD_CONTACTS_FAILURE'